---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.2
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner
      tag: v4.0.2
    nfs:
      server: 10.0.100.168
      path: /data
    # resources:
    #   requests:
    #     cpu: 100m
    #     memory: 128Mi
    #   limits:
    #     memory: 256Mi
